### ISSUE TITLE
Update streaming strategy

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/encrypted-stream-name#5]
### Descriptive summary

Decision was made to use the default Hyrax persistence strategy for derivatives.

The streaming plugin should not assume files to be streaming from Fedora, but rather from a single derivatives area on the filestore (presumably Isilon).

### Related work

https://github.com/ucsdlib/horton/issues/47
https://github.com/ucsdlib/horton/issues/11

**Comment by lsitu** [comment]
@mcritchlow I've created a [PR 6](https://github.com/ucsdlib/encrypted-stream-name/pull/6) for the change we need. It's ready for review now. Thanks.
