### ISSUE TITLE
Create a DAMS4 branch to deploy from

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/encrypted-stream-name#7]
We've already started updating this repository for DAMS5, but it also contains the history for DAMS4 usage as well. I think we need to just confirm the last commit that was dedicated to DAMS4.

I believe that commit is https://github.com/ucsdlib/encrypted-stream-name/commit/1b987ae45b555ba34dbf2e5f77f05e9aab8f6e11 

Could @lsitu and/or @VivianChu take a peek and confirm when you have a chance?

Assuming that's true, I'll create a branch off of that commit that we can use for `dams4` going forward, should other commits be needed.

**Comment by lsitu** [comment]
@mcritchlow Yes. Commit https://github.com/ucsdlib/encrypted-stream-name/commit/1b987ae45b555ba34dbf2e5f77f05e9aab8f6e11 is the last commit for DAMS4. And the commits after it are what we've added for DAMS5.

**Comment by mcritchlow** [comment]
@lsitu - Great, thanks! What do you think about including one more commit up, so we also inherit the LICENSE?

**Comment by mcritchlow** [comment]
Ok, we're good to go here. I'm going to work with @rstanonik on making sure we can deploy from the newly created [`dams4` branch](https://github.com/ucsdlib/encrypted-stream-name/tree/dams4).
